-- 1. Установите Arend, следуя инструкциям на странице:
-- https://arend-lang.github.io/documentation/getting-started/download
-- В IDEA можно просто импортировать данный проект

-- 2. Определите аналоги следующих функций на языке Haskell
{- Haskell:
   second :: Nat -> Nat -> Nat -> Nat
   second _ y _ = y

   apply :: (Nat -> Nat) -> Nat -> Nat
   apply f x = f x

   compose :: (Nat -> Nat) -> (Nat -> Nat) -> Nat -> Nat
   compose f g x = f (g x)

   flip :: (Nat -> Nat -> Nat) -> Nat -> Nat -> Nat
   flip f x y = f y x

   second' = flip (second 0)
-}
\func second (_ : Nat) (y : Nat) (_ : Nat) : Nat => y

\func apply (f : Nat -> Nat) (x : Nat) => f x

\func compose (f : Nat -> Nat) (g : Nat -> Nat) (x : Nat) : Nat => f (g x)

\func flip (f : Nat -> Nat -> Nat) (x : Nat) (y : Nat) : Nat => f y x

\func second' => flip (second 0)

-- 3. Расставьте приоритеты функций f1, f2, f3, f4, f5 и f6 так, чтобы функция test проходила тайпчекинг

\import lect01 \hiding (+, *)

\func \fixl 6 f1 (x y : Nat) => x
\func \fixl 6 f2 : Nat => 0
\func \infixl 1 f3 (f : Nat -> Nat) (z : Nat) : Int => 0
\func \fixl 6 f4 : Nat => 0
\func \infixl 8 f5 => f1
\func \fixl 6 f6 => f4

\func test => f1 f2 f3 f4 f5 f6

-- 4. Определите функцию if, аналогичную следующей функции:
{- Haskell:
   if :: Bool -> Bool -> Bool -> Bool
   if True t _ = t
   if False _ e = e
-}

\func if (cond : Bool) (onT : Bool) (onF : Bool) : Bool \elim cond
  | true => onT
  | false => onF

-- 5. Определите || через if

\func \infixr 2 || (x y : Bool) : Bool => if x true y

-- 6. Определите возведение в степень и факториал для натуральных чисел

\open Nat \hiding (-, div) -- Здесь лежат + и *

\func \infixr 8 ^ (x y : Nat) : Nat \elim y
  | suc y' => x * (x ^ y')
  | zero => 1

\func fac (x : Nat) : Nat \elim x
  | zero => 1
  | suc x' => (x' + 1) * fac x'

-- 7. Определите mod и gcd

\func mod (x y : Nat) : Nat \elim y
  | zero => zero
  | y => x - div x y * y

\func gcd (x y : Nat) : Nat => aux x x y
  \where
    \func aux (fuel x y : Nat) : Nat \elim fuel, x
      | zero, _ => y
      | suc _, zero => y
      | suc f', x => aux f' (mod y x) x