\import Data.Bool
\import Data.List
\import Data.Or
\import Logic
\import Order.PartialOrder
\import hw01 (fac)

-- 1. Определите полиморфный tail для списков

\func tail' {A : \Type} (l : List A) : List A \elim l
  | nil => nil
  | (_ :: xs) => xs


-- 2. Реализуйте любой (but choose wisely) алгоритм сортировки. Функцию сравнения можно принимать в качестве аргумента

\func sort {A : \Type} (comp : A -> A -> Bool) (l : List A) =>
  sort' l
  \where {
    \func sort' (l : List A) : List A \elim l
      | nil => nil
      | a1 :: l' => sortInsert (sort' l') a1

    \func sortInsert (l : List A) (a : A) : List A \elim l
      | nil => a :: nil
      | a1 :: l' => \case comp a1 a \with {
        | false => a1 :: sortInsert l' a
        | true => a :: a1 :: l'
      }
  }

-- 3. Докажите ассоциативность && и ||

\func &&-assoc (x y z : Bool) : (x and y) and z = x and (y and z) \elim x, y, z
  | false, false, false => idp
  | false, false, true => idp
  | false, true, false => idp
  | false, true, true => idp
  | true, false, false => idp
  | true, false, true => idp
  | true, true, false => idp
  | true, true, true => idp

\func ||-assoc (x y z : Bool) : (x or y) or z = x or (y or z) \elim x, y, z
  | false, false, false => idp
  | false, false, true => idp
  | false, true, false => idp
  | false, true, true => idp
  | true, false, false => idp
  | true, false, true => idp
  | true, true, false => idp
  | true, true, true => idp

-- 4. Докажите, что fac 3 равно 6

\func fac-3=6 : fac 3 = 6 => idp

-- 5. Докажите следующие пропозициональные тавтологии (можно решить любые 2 из 3 задач)

-- t1 : (P and Q -> R) -> P -> Q -> R

\func t1 {P Q R : \Type} (f : \Sigma P Q -> R) (p : P) (q : Q) : R => f (p, q)

-- t2 : (P -> R) -> (Q -> R) -> P or Q -> R

\func t2 {P Q R : \Type} (f : P -> R) (g : Q -> R) (h : Or P Q) : R \elim h
  | inl a => f a
  | inr b => g b

-- t3 : ((P -> Q -> R) -> P) -> (P -> R) -> R

\func t3 {P Q R : \Type} (f : (P -> Q -> R) -> P) (g : P -> R) : R =>
  g (f (\lam x _ => g x))

-- 6. Сформулируйте и докажите следующие пропозициональные тавтологии (можно решить любые 2 из 3 задач)

-- t4 : (P -> Q -> R) -> P /\ Q -> R
-- t5 : (P or Q -> P /\ Q) -> (P -> Q) /\ (Q -> P)
-- t6 : ((((P -> Q) -> P) -> P) -> Q) -> Q

\func t4 {P Q R : \Type} (f : P -> Q -> R) (x : \Sigma P Q) : R => f x.1 x.2

\func t5 {P Q : \Type} (f : Or P Q -> \Sigma P Q) : \Sigma (P -> Q) (Q -> P)
  => (\lam p => (f (inl p)).2, \lam q => (f (inr q)).1)

-- 7. Докажите следующие утверждения

-- s1 : Если для любого x : Nat верно P(x), то существует x : Nat для которого P(x) верно

\func s1 (P : Nat -> \Type) (h : \Pi (x : Nat) -> P x) : \Sigma (x : Nat) (P x) => (0, h 0)

-- s2 : Если не существует x : Nat такого, что верно P(x), то P(3) не верно

\func s2 (P : Nat -> \Type) (h : \Sigma (x : Nat) (P x) -> Empty) : P 3 -> Empty => \lam p => h (3, p)

-- 8. Сформулируйте и докажите следующие утверждения

-- s3 : Если для всех x : Nat верно, что P(x) влечет Q(x), и существует x : Nat для которого верно P(x),
-- то существует x : Nat для которого верно Q(x)

\func s3 (P Q : Nat -> \Type) (h : \Pi (x : Nat) -> P x -> Q x) (x : Nat) (px : P x) : \Sigma (y : Nat) (Q y)
  => (x, h x px)

-- s4 : Если для всех x : Nat либо не верно P(x), либо не верно Q(x), то P(3) влечет, что Q(3) не верно

\func s4 (P Q : Nat -> \Type) (h : \Pi (x : Nat) -> Or (P x -> Empty) (Q x -> Empty)) : P 3 -> Q 3 -> Empty
  => \lam p3 => \case h 3 \with {
    | inl a => \lam _ => a p3
    | inr b => b
  }
